from randomwalk_app import app, db
from randomwalk_app import Exercise, ExerciseEntry
from random import randint
from datetime import datetime, timedelta


with app.app_context():
    db.create_all()

    # Prepopulate exercises
    exercises = [
        Exercise(name='Push-ups', min_repetitions=10, max_repetitions=20, min_weight=0, max_weight=0),
        Exercise(name='Squats', min_repetitions=10, max_repetitions=20, min_weight=0, max_weight=0),
        Exercise(name='Lunges', min_repetitions=10, max_repetitions=20, min_weight=0, max_weight=0),
        Exercise(name='Burpees', min_repetitions=10, max_repetitions=20, min_weight=0, max_weight=0),
        Exercise(name='Plank', min_repetitions=30, max_repetitions=60, min_weight=0, max_weight=0),
        Exercise(name='Dumbbell Curls', min_repetitions=8, max_repetitions=12, min_weight=5, max_weight=25),
        Exercise(name='Dumbbell Shoulder Press', min_repetitions=8, max_repetitions=12, min_weight=5, max_weight=25),
        Exercise(name='Dumbbell Rows', min_repetitions=8, max_repetitions=12, min_weight=5, max_weight=25),
        Exercise(name='Dumbbell Squats', min_repetitions=8, max_repetitions=12, min_weight=5, max_weight=25),
        Exercise(name='Dumbbell Lunges', min_repetitions=8, max_repetitions=12, min_weight=5, max_weight=25),
        Exercise(name='Bench Press', min_repetitions=8, max_repetitions=12, min_weight=50, max_weight=200),
        Exercise(name='Deadlifts', min_repetitions=6, max_repetitions=10, min_weight=50, max_weight=300),
        Exercise(name='Barbell Squats', min_repetitions=8, max_repetitions=12, min_weight=50, max_weight=200),
        Exercise(name='Pull-ups', min_repetitions=5, max_repetitions=10, min_weight=0, max_weight=0),
        Exercise(name='Chin-ups', min_repetitions=5, max_repetitions=10, min_weight=0, max_weight=0),
        Exercise(name='Russian Twists', min_repetitions=20, max_repetitions=30, min_weight=0, max_weight=0),
        Exercise(name='Leg Press', min_repetitions=10, max_repetitions=15, min_weight=50, max_weight=400),
        Exercise(name='Hamstring Curls', min_repetitions=10, max_repetitions=15, min_weight=10, max_weight=80),
        Exercise(name='Calf Raises', min_repetitions=15, max_repetitions=20, min_weight=0, max_weight=0),
        Exercise(name='Bicycle Crunches', min_repetitions=20, max_repetitions=30, min_weight=0, max_weight=0),
        Exercise(name='Mountain Climbers', min_repetitions=20, max_repetitions=30, min_weight=0, max_weight=0),
        Exercise(name='Jumping Jacks', min_repetitions=20, max_repetitions=30, min_weight=0, max_weight=0),
        Exercise(name='High Knees', min_repetitions=20, max_repetitions=30, min_weight=0, max_weight=0),
        Exercise(name='Tricep Dips', min_repetitions=8, max_repetitions=12, min_weight=0, max_weight=0),
        Exercise(name='Shoulder Taps', min_repetitions=10, max_repetitions=20, min_weight=0, max_weight=0),
        Exercise(name='Side Planks', min_repetitions=30, max_repetitions=60, min_weight=0, max_weight=0),
        Exercise(name='Bicep Curls', min_repetitions=8, max_repetitions=12, min_weight=5, max_weight=25),
        Exercise(name='Tricep Extensions', min_repetitions=8, max_repetitions=12, min_weight=5, max_weight=25),
        Exercise(name='Front Raises', min_repetitions=8, max_repetitions=12, min_weight=5, max_weight=25),
        Exercise(name='Lateral Raises', min_repetitions=8, max_repetitions=12, min_weight=5, max_weight=25),
        Exercise(name='Hammer Curls', min_repetitions=8, max_repetitions=12, min_weight=5, max_weight=25),
        Exercise(name='Step-ups', min_repetitions=10, max_repetitions=15, min_weight=0, max_weight=0),
        Exercise(name='Chest Press', min_repetitions=8, max_repetitions=12, min_weight=50, max_weight=200),
        Exercise(name='Incline Bench Press', min_repetitions=8, max_repetitions=12, min_weight=50, max_weight=200),
        Exercise(name='Shoulder Press', min_repetitions=8, max_repetitions=12, min_weight=50, max_weight=200),
        Exercise(name='Lat Pulldowns', min_repetitions=8, max_repetitions=12, min_weight=50, max_weight=200),
        Exercise(name='Seated Cable Rows', min_repetitions=8, max_repetitions=12, min_weight=50, max_weight=200),
        Exercise(name='Leg Extensions', min_repetitions=10, max_repetitions=15, min_weight=20, max_weight=120),
        Exercise(name='Hip Thrusts', min_repetitions=10, max_repetitions=15, min_weight=0, max_weight=0),
        Exercise(name='Crunches', min_repetitions=20, max_repetitions=30, min_weight=0, max_weight=0),
        Exercise(name='Reverse Crunches', min_repetitions=20, max_repetitions=30, min_weight=0, max_weight=0),
        Exercise(name='Plank Jacks', min_repetitions=20, max_repetitions=30, min_weight=0, max_weight=0),
        Exercise(name='Supermans', min_repetitions=10, max_repetitions=15, min_weight=0, max_weight=0),
        Exercise(name='Skull Crushers', min_repetitions=8, max_repetitions=12, min_weight=5, max_weight=25),
        Exercise(name='Hanging Leg Raises', min_repetitions=10, max_repetitions=15, min_weight=0, max_weight=0),
        Exercise(name='Dumbbell Bench Press', min_repetitions=8, max_repetitions=12, min_weight=5, max_weight=25),
        Exercise(name='Dumbbell Flyes', min_repetitions=8, max_repetitions=12, min_weight=5, max_weight=25),
        Exercise(name='Hammer Strength Press', min_repetitions=8, max_repetitions=12, min_weight=50, max_weight=200),
        Exercise(name='Pec Deck', min_repetitions=10, max_repetitions=15, min_weight=0, max_weight=0),
        Exercise(name='Good Mornings', min_repetitions=8, max_repetitions=12, min_weight=50, max_weight=200),
        Exercise(name='Side Lunges', min_repetitions=10, max_repetitions=20, min_weight=0, max_weight=0),
        Exercise(name='Cable Crossover', min_repetitions=10, max_repetitions=15, min_weight=0, max_weight=0),
        Exercise(name='Dumbbell Pullover', min_repetitions=8, max_repetitions=12, min_weight=5, max_weight=25),
        Exercise(name='Rear Delt Flyes', min_repetitions=8, max_repetitions=12, min_weight=5, max_weight=25),
        Exercise(name='Bent-Over Rows', min_repetitions=8, max_repetitions=12, min_weight=50, max_weight=200),
        Exercise(name='Wide-Grip Pull-ups', min_repetitions=5, max_repetitions=10, min_weight=0, max_weight=0),
        Exercise(name='Dips', min_repetitions=5, max_repetitions=10, min_weight=0, max_weight=0),
        Exercise(name='Inverted Rows', min_repetitions=8, max_repetitions=12, min_weight=0, max_weight=0),
        Exercise(name='Kettlebell Swings', min_repetitions=10, max_repetitions=15, min_weight=10, max_weight=50),
        Exercise(name='Single-Leg Romanian Deadlifts', min_repetitions=8, max_repetitions=12, min_weight=0, max_weight=0),
        Exercise(name='Side Plank Hip Lifts', min_repetitions=10, max_repetitions=15, min_weight=0, max_weight=0),
        Exercise(name='Russian Twists', min_repetitions=20, max_repetitions=30, min_weight=0, max_weight=0),
        Exercise(name='Leg Press', min_repetitions=10, max_repetitions=15, min_weight=50, max_weight=400),
        Exercise(name='Hamstring Curls', min_repetitions=10, max_repetitions=15, min_weight=10, max_weight=80),
        Exercise(name='Calf Raises', min_repetitions=15, max_repetitions=20, min_weight=0, max_weight=0),
        Exercise(name='Bicycle Crunches', min_repetitions=20, max_repetitions=30, min_weight=0, max_weight=0),
        Exercise(name='Mountain Climbers', min_repetitions=20, max_repetitions=30, min_weight=0, max_weight=0),
        Exercise(name='Jumping Jacks', min_repetitions=20, max_repetitions=30, min_weight=0, max_weight=0),
        Exercise(name='High Knees', min_repetitions=20, max_repetitions=30, min_weight=0, max_weight=0),
        Exercise(name='Tricep Dips', min_repetitions=8, max_repetitions=12, min_weight=0, max_weight=0),
        Exercise(name='Shoulder Taps', min_repetitions=10, max_repetitions=20, min_weight=0, max_weight=0),
        Exercise(name='Side Planks', min_repetitions=30, max_repetitions=60, min_weight=0, max_weight=0),
        Exercise(name='Bicep Curls', min_repetitions=8, max_repetitions=12, min_weight=5, max_weight=25),
        Exercise(name='Tricep Extensions', min_repetitions=8, max_repetitions=12, min_weight=5, max_weight=25),
        Exercise(name='Front Raises', min_repetitions=8, max_repetitions=12, min_weight=5, max_weight=25),
        Exercise(name='Lateral Raises', min_repetitions=8, max_repetitions=12, min_weight=5, max_weight=25),
        Exercise(name='Hammer Curls', min_repetitions=8, max_repetitions=12, min_weight=5, max_weight=25),
        Exercise(name='Step-ups', min_repetitions=10, max_repetitions=15, min_weight=0, max_weight=0),
        Exercise(name='Chest Press', min_repetitions=8, max_repetitions=12, min_weight=50, max_weight=200),
        Exercise(name='Incline Bench Press', min_repetitions=8, max_repetitions=12, min_weight=50, max_weight=200),
        Exercise(name='Shoulder Press', min_repetitions=8, max_repetitions=12, min_weight=50, max_weight=200),
        Exercise(name='Lat Pulldowns', min_repetitions=8, max_repetitions=12, min_weight=50, max_weight=200),
        Exercise(name='Seated Cable Rows', min_repetitions=8, max_repetitions=12, min_weight=50, max_weight=200),
        Exercise(name='Leg Extensions', min_repetitions=10, max_repetitions=15, min_weight=20, max_weight=120),
        Exercise(name='Hip Thrusts', min_repetitions=10, max_repetitions=15, min_weight=0, max_weight=0),
        Exercise(name='Crunches', min_repetitions=20, max_repetitions=30, min_weight=0, max_weight=0),
        Exercise(name='Reverse Crunches', min_repetitions=20, max_repetitions=30, min_weight=0, max_weight=0),
        Exercise(name='Plank Jacks', min_repetitions=20, max_repetitions=30, min_weight=0, max_weight=0),
        Exercise(name='Supermans', min_repetitions=10, max_repetitions=15, min_weight=0, max_weight=0),
        Exercise(name='Skull Crushers', min_repetitions=8, max_repetitions=12, min_weight=5, max_weight=25),
        Exercise(name='Hanging Leg Raises', min_repetitions=10, max_repetitions=15, min_weight=0, max_weight=0),
        Exercise(name='Dumbbell Bench Press', min_repetitions=8, max_repetitions=12, min_weight=5, max_weight=25),
        Exercise(name='Dumbbell Flyes', min_repetitions=8, max_repetitions=12, min_weight=5, max_weight=25)
    ]

    db.session.add_all(exercises)

    exercise_entries = [
        ExerciseEntry(name='Push-ups', repetitions=randint(10, 20), weight=randint(0, 10), timestamp=datetime.utcnow() - timedelta(days=7)),
        ExerciseEntry(name='Squats', repetitions=randint(10, 20), weight=randint(0, 10), timestamp=datetime.utcnow() - timedelta(days=6)),
        ExerciseEntry(name='Lunges', repetitions=randint(10, 20), weight=randint(0, 10), timestamp=datetime.utcnow() - timedelta(days=5)),
        ExerciseEntry(name='Burpees', repetitions=randint(10, 20), weight=randint(0, 10), timestamp=datetime.utcnow() - timedelta(days=4)),
        ExerciseEntry(name='Plank', repetitions=randint(10, 20), weight=randint(0, 10), timestamp=datetime.utcnow() - timedelta(days=3)),
        ExerciseEntry(name='Dumbbell Curls', repetitions=randint(8, 12), weight=randint(5, 25), timestamp=datetime.utcnow() - timedelta(days=2)),
        ExerciseEntry(name='Dumbbell Shoulder Press', repetitions=randint(8, 12), weight=randint(5, 25), timestamp=datetime.utcnow() - timedelta(days=1)),
        ExerciseEntry(name='Dumbbell Rows', repetitions=randint(8, 12), weight=randint(5, 25), timestamp=datetime.utcnow()),
        ExerciseEntry(name='Dumbbell Squats', repetitions=randint(8, 12), weight=randint(5, 25), timestamp=datetime.utcnow()),
        ExerciseEntry(name='Dumbbell Lunges', repetitions=randint(8, 12), weight=randint(5, 25), timestamp=datetime.utcnow())
    ]

    db.session.add_all(exercise_entries)
    
    db.session.commit()
